---
title: TpebaTak
description: Даю собі можливість зробити щось справді потрібне.
disqus_shortname: trebatak
reading_time: true
words_per_minute: 200
url: https://vokov.treba.tk
owner:
  name: Володимир Коваленко
  avatar: avatar.jpg
  bio: Батько. Син. Чоловік. Інженер. Громадянин.
  email: kroschu@mail.ua
  twitter: kroschu
  facebook: 
  github: kroschu
  stackexchange: 
  linkedin: kroschu
  instagram: kroschu
  flickr: 
  tumblr: 
  google_plus: 
background: 
svg:
  optimize: true
webmaster_verifications:
  google: jSLDwBQBJe00Al-2gkR-sTDQdxaVPsI1o8AflDTxga8
  bing: 1234
  alexa: 1234
  yandex: 60284d8f500077cd
  baidu: 1234
google_analytics: 
google_verify: 
bing_verify: 
timezone: Europe/Kiev
future: false
highlighter: rouge
markdown: kramdown
plugins:
- jekyll-inline-svg
- jekyll-toc
- jekyll-sitemap
- jekyll-paginate
- jekyll-gist
- jekyll-feed
- jekyll-seo-tag
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
paginate: 5
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
include:
- ".htaccess"
exclude:
- "*.less"
- "*.sublime-project"
- "*.sublime-workspace"
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- CHANGELOG
- Capfile
- Gemfile
- Gruntfile.js
- LICENSE
- README
- Rakefile
- config
- gulpfile.js
- lib
- log
- node_modules
- package.json
- spec
- tmp
